(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d,f="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},g=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},h=g(this),k;
if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var m={R:!0},n={};try{n.__proto__=m;l=n.R;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=k;var u=function(a,b){var c=void 0===c?null:c;var e=document.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,c);b.dispatchEvent(e)};var w=function(a){if(!a.gwdIsLoaded()){var b=v(a);b?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad()}},x=function(a){if(!a.gwdIsActive()){var b=v(a);b?b.gwdIsActive()&&a.gwdActivate():a.gwdActivate()}},y=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},v=function(a){if(y(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&y(a))return a;return null};var z=function(a){return Math.min(Math.max(a,1),Infinity)};var A={U:"alignment",V:"autoplay",W:"clipheight",X:"clipwidth",Y:"duration",Z:"endonstartframe",$:"imagesource",aa:"loopcount",ba:"offsetx",ca:"offsety",da:"quickready",ea:"reverseplay",fa:"scaling",ga:"totalframecount"},B=[],C=0,D;for(D in A)B[C++]=A[D];
var E=function(){var a=HTMLElement.call(this)||this;a.S="gwd_spritesheet_"+(2147483648*Math.random()|0);a.a=null;a.B=!1;a.J=!1;a.j=null;a.O=0;a.N=0;a.H="";a.C=0;a.K=0;a.c=64;a.g=64;a.I=0;a.T=0;a.l=!1;a.P=!1;a.s=!1;a.f=1;a.o=100;a.i=0;a.b=0;a.m=0;a.h=!1;a.L=0;a.A=0;a.F=0;a.D=0;a.v="auto";a.M="top left";a.G=null;a.u=!1;return a},F=HTMLElement;E.prototype=f(F.prototype);E.prototype.constructor=E;
if(t)t(E,F);else for(var G in F)if("prototype"!=G)if(Object.defineProperties){var H=Object.getOwnPropertyDescriptor(F,G);H&&Object.defineProperty(E,G,H)}else E[G]=F[G];d=E.prototype;
d.connectedCallback=function(){for(;this.firstChild;)this.removeChild(this.firstChild);this.a=this.ownerDocument.createElement("canvas");this.a.className=this.S;this.appendChild(this.a);this.O=parseInt(window.getComputedStyle(this,null).getPropertyValue("width"),10);this.N=parseInt(window.getComputedStyle(this,null).getPropertyValue("height"),10);this.l=this.hasAttribute("autoplay");this.P=this.hasAttribute("endonstartframe");this.s=this.hasAttribute("reverseplay");this.G=this.a.getContext("2d");
this.u=!0;I(this);J(this);w(this)};
d.attributeChangedCallback=function(a,b,c){switch(a){case "imagesource":this.u&&this.pause();this.H=c||"";this.u&&(this.B=!1,w(this));break;case "offsetx":this.C=parseInt(c,10);break;case "offsety":this.K=parseInt(c,10);break;case "clipwidth":this.c=z(parseInt(c,10));I(this);break;case "clipheight":this.g=z(parseInt(c,10));I(this);break;case "scaling":c?(this.v=c,I(this)):this.setAttribute(a,"auto");break;case "alignment":c?(this.M=c,J(this)):this.setAttribute(a,"top left");break;case "totalframecount":this.f=
z(parseInt(c,10));break;case "duration":this.o=z(parseInt(c,10));break;case "loopcount":this.i=parseInt(c,10);break;case "autoplay":(this.l="true"==c)?this.play():this.pause()}};d.gwdLoad=function(){/^[\s\xa0]*$/.test(this.H)?(this.B=!0,u("ready",this),x(this)):(K(this),this.hasAttribute("quickready")&&u("ready",this))};d.gwdIsLoaded=function(){return this.B};d.gwdActivate=function(){this.l?this.gwdIsLoaded()&&this.play():this.gwdIsLoaded()&&L(this,0);this.J=!0};
d.gwdDeactivate=function(){this.pause();this.J=!1};d.gwdIsActive=function(){return this.J};
var L=function(a,b){if(a.j){var c=z(Math.floor((a.I-a.C)/a.c)),e=z(Math.floor(a.I/a.c)),p=a.C,q=a.K,r=b;b>=c&&(r=(b-c)%e,p=0,q+=a.g*Math.floor(1+(b-c)/e));a.G.clearRect(0,0,a.c,a.g);a.G.drawImage(a.j,p+r*a.c,q,a.c,a.g,0,0,a.c,a.g)}},I=function(a){if(a.u){var b=a.O/a.c,c=a.N/a.g;"100% 100%"==a.v?(a.a.style.width="100%",a.a.style.height="100%",a.style.overflow="visible"):"contain"==a.v?(b=b<c?b:c,a.a.style.width=a.c*b+"px",a.a.style.height=a.g*b+"px",a.style.overflow="visible"):("cover"==a.v?(b=b<c?
c:b,a.a.style.width=a.c*b+"px",a.a.style.height=a.g*b+"px"):(a.a.style.width=a.c+"px",a.a.style.height=a.g+"px"),a.style.overflow="hidden");a.a.width=a.c;a.a.height=a.g}},J=function(a){if(a.u&&"100% 100%"!=a.v){var b=parseInt(a.a.style.width,10),c=parseInt(a.a.style.height,10);a.style.position="absolute;";a.a.style.position="relative";switch(a.M){case "center":a.a.style.left="50%";a.a.style.top="50%";a.a.style.transform="translate(-"+b/2+"px, -"+c/2+"px)";break;case "bottom":a.a.style.left="50%";
a.a.style.top="100%";a.a.style.transform="translate(-"+b/2+"px, -"+c+"px)";break;case "bottom left":a.a.style.left="0%";a.a.style.top="100%";a.a.style.transform="translate(0px, -"+c+"px)";break;case "bottom right":a.a.style.left="100%";a.a.style.top="100%";a.a.style.transform="translate(-"+b+"px, -"+c+"px)";break;case "left":a.a.style.left="0%";a.a.style.top="50%";a.a.style.transform="translate(0px, -"+c/2+"px)";break;case "right":a.a.style.left="100%";a.a.style.top="50%";a.a.style.transform="translate(-"+
b+"px, -"+c/2+"px)";break;case "top":a.a.style.left="50%";a.a.style.top="0%";a.a.style.transform="translate(-"+b/2+"px, 0px)";break;case "top left":a.a.style.top="0%";a.a.style.left="0%";a.a.style.transform="translate(0px, 0px)";break;case "top right":a.a.style.top="0%",a.a.style.left="100%",a.a.style.transform="translate(-"+b+"px, 0px)"}}},M=function(a){a.h&&(L(a,a.b),a.s?(a.b=(a.b-1+a.f)%a.f,a.b==a.f-1&&a.m++):(a.b==a.f-1&&a.m++,a.b=(a.b+1)%a.f),a.i=parseInt(a.i,10),a.m<a.i||0==a.i?(a.A+=a.o,a.F=
(new Date).getTime()-a.L-a.A,a.D=setTimeout(function(){M(a)},a.o-a.F)):a.D=1==a.P?setTimeout(function(){a.s?a.goToFrame(a.f-1):a.goToFrame(0);u("animationend",a)},a.o):setTimeout(function(){a.h=!1;u("animationend",a)},a.o))},N=function(a){a.L=+new Date;a.A=-a.o;a.F=0;clearTimeout(a.D)},K=function(a){a.j=new Image;a.j.addEventListener("load",function(){a.I=parseInt(a.j.naturalWidth,10);a.T=parseInt(a.j.naturalHeight,10);N(a);a.s&&(a.b=a.f-1);L(a,a.b);1==a.l&&(a.h=!0,M(a));a.B=!0;u("ready",a);x(a)});
a.j.src=a.H};d=E.prototype;d.getImage=function(){return this.j};d.getCurrentFrame=function(){return this.b};d.newAnimation=function(a,b,c,e,p,q,r,O,P){this.C=parseInt(a,10);this.K=parseInt(b,10);this.s=P;this.l=O;this.f=parseInt(p,10);this.o=parseInt(q,10);this.i=parseInt(r,10);this.m=this.b=0;a=z(parseInt(c,10));e=z(parseInt(e,10));if(a!=this.c||e!=this.g)this.c=a,this.g=e,I(this);1==this.s&&(this.b=this.f-1);this.m=0;1==this.l?this.restart():(this.h=!1,L(this,0))};
d.goToFrame=function(a){0>a&&(a=this.f-Math.abs(a)%this.f);this.b=a%this.f;L(this,this.b);this.h=!1};d.play=function(){(this.m<this.i||0==this.i)&&0==this.h&&(u("animationplay",this),this.h=!0,N(this),M(this))};d.pause=function(){this.h&&(u("animationpause",this),this.h=!1)};d.togglePlay=function(){0==this.h?this.play():this.pause()};d.restart=function(){u("animationrestart",this);this.b=0;this.s&&(this.b=this.f-1);this.m=0;0==this.h&&this.play()};d.previousFrame=function(){this.b--;this.goToFrame(this.b)};
d.nextFrame=function(){this.b++;this.goToFrame(this.b)};h.Object.defineProperties(E,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return B}}});customElements.define("gwd-spritesheet",E);}).call(this);
