(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var d="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},f=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},g=f(this),h;
if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var l;a:{var m={a:!0},n={};try{n.__proto__=m;l=n.a;break a}catch(a){}l=!1}h=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var p=h;var q=function(a){a=parseFloat(a.getAttribute("time-limit"));isFinite(a)||(a=-1);return 0<a?a:-1},r=function(a,b,c){return a.hasAttribute(b)?a.getAttribute(b):c};var t=["gwd-before-and-after","gwd-breathe","gwd-reveal","gwd-wave"];var u=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},v=function(a){if(u(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&u(a))return a;return null},w=function(a){return(a=r(a,"images",""))?a.split(",").map(function(b){return b.trim()}):[]};var x=function(a,b){var c=void 0===c?null:c;var e=document.createEvent("CustomEvent");e.initCustomEvent(a,!0,!0,c);b.dispatchEvent(e)};var y=["images"],z=function(){var a=HTMLElement.call(this)||this;a.images=[];a.s=!1;a.K=0;a.v=1;a.A=-1;a.J=a.H.bind(a);a.I=a.P.bind(a);a.O=a.T.bind(a);a.N=a.S.bind(a);a.M=a.R.bind(a);a.l=!1;a.B=0;a.F=!1;a.h=null;a.D=null;return a},A=HTMLElement;z.prototype=d(A.prototype);z.prototype.constructor=z;if(p)p(z,A);else for(var B in A)if("prototype"!=B)if(Object.defineProperties){var C=Object.getOwnPropertyDescriptor(A,B);C&&Object.defineProperty(z,B,C)}else z[B]=A[B];
z.prototype.connectedCallback=function(){var a=this;this.F=!0;this.C=this.clientWidth;this.u=this.clientHeight;this.j=w(this);this.G=r(this,"scaling","cover");this.A=1E3*q(this);setTimeout(function(){a.firstElementChild&&-1!==t.indexOf(a.firstElementChild.tagName.toLowerCase())&&(a.g=a.firstElementChild);void 0===a.i&&(a.i=a.ownerDocument.createElement("canvas"),a.appendChild(a.i));D(a,a.i);void 0===a.m&&(a.m=a.ownerDocument.createElement("gwd-gesture"),a.appendChild(a.m));if(a.g){var b=a.m;b.addEventListener("pointerover",
a.O,!1);b.addEventListener("pointerout",a.N,!1);b.addEventListener("pointermove",a.M,!1)}a.gwdIsLoaded()&&a.g?(a.h&&(cancelAnimationFrame(a.h),a.h=null),E(a)):a.gwdIsLoaded()||((b=v(a))?b.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad())})};z.prototype.attributeChangedCallback=function(a,b,c){b!==c&&this.gwdIsLoaded()&&(this.j=w(this),this.s=!1,F(this))};z.prototype.T=function(a){void 0===a.offsetX&&(this.D=this.getBoundingClientRect());G(this,a)};z.prototype.S=function(){this.g.handlePointerOut()};
z.prototype.R=function(a){void 0!==this.o&&(G(this,a),this.l&&this.g.shouldRenderOnHoverWhilePaused()&&this.g.render(this.L-this.B-this.o))};var G=function(a,b){if(void 0!==b.offsetX){var c=b.offsetX/a.C;b=b.offsetY/a.u}else c=(b.clientX-a.D.left)/a.C,b=(b.clientY-a.D.top)/a.u;c=Math.max(0,Math.min(1,c));b=Math.max(0,Math.min(1,b));a.g.handlePointerUpdate(c,b)};
z.prototype.disconnectedCallback=function(){this.F=!1;if(this.m){var a=this.m;a.removeEventListener("pointerover",this.O,!1);a.removeEventListener("pointerout",this.N,!1);a.removeEventListener("pointermove",this.M,!1)}};z.prototype.gwdLoad=function(){F(this)};z.prototype.gwdIsLoaded=function(){return this.s};
var F=function(a){if(a.j.length){a.K=0;a.images=[];for(var b=0;b<a.j.length;b++){var c=a.ownerDocument.createElement("img");c.addEventListener("load",a.J,!1);c.addEventListener("error",a.I,!1);a.images.push(c);a.j[b]?c.src=a.j[b]:a.H()}}else a.s=!0,x("ready",a)};
z.prototype.H=function(){var a=this;if(++this.K===this.j.length){H(this);for(var b=[],c=0;c<this.images.length;c++){var e=I(this,this.images[c]);b.push(e)}this.g?(this.g.initialize(b,this.images,this.v),this.h=requestAnimationFrame(function(){E(a)})):this.i.getContext("2d").drawImage(b[0],0,0,this.i.width,this.i.height)}};z.prototype.P=function(){H(this);this.images=[]};
var H=function(a){for(var b=0;b<a.images.length;b++){var c=a.images[b];c.removeEventListener("load",a.J,!1);c.removeEventListener("error",a.I,!1)}a.s=!0;x("ready",a)},E=function(a){if(0!==a.C&&0!==a.u&&!a.l&&!1!==a.F){void 0===a.o&&(a.o=Date.now());var b=Date.now()-a.o-a.B;0<a.A&&b>a.A?(a.pause(),x("autoplayended",a)):(a.g.render(b),a.h=requestAnimationFrame(function(){E(a)}))}},D=function(a,b){a.v=window.devicePixelRatio;b.width=a.C*a.v;b.height=a.u*a.v},I=function(a,b){var c=a.ownerDocument.createElement("canvas");
D(a,c);var e=c.getContext("2d");switch(a.G){case "stretch":e.drawImage(b,0,0,c.width,c.height);break;default:var k=1;"contain"===a.G?k=Math.min(c.width/b.naturalWidth,c.height/b.naturalHeight):"none"!==a.G&&(k=Math.max(c.width/b.naturalWidth,c.height/b.naturalHeight));e.save();e.translate(c.width/2,c.height/2);e.scale(k,k);e.drawImage(b,-b.naturalWidth/2,-b.naturalHeight/2);e.restore()}return c};z.prototype.pause=function(){this.l||(this.L=Date.now(),this.l=!0,this.A=-1)};
z.prototype.play=function(){var a=this;this.l&&(this.l=!1,this.h=requestAnimationFrame(function(){a.B+=Date.now()-a.L;E(a)}))};g.Object.defineProperties(z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return y}}});customElements.define("gwd-image-effect",z);}).call(this);
